VIA_ENABLE = yes
TAP_DANCE_ENABLE = yes
BOOTMAGIC_ENABLE = yes

EMOTICON_ENABLE = yes
ENCODER_DEFAULTACTIONS_ENABLE = no
IDLE_TIMEOUT_ENABLE = yes
STARTUP_NUMLOCK_ON = yes
TD_LSFT_CAPSLOCK_ENABLE = yes

INVERT_NUMLOCK_INDICATOR = yes
# DEBOUNCE_TYPE = sym_eager_pk
NKRO_ENABLE = yes
